### ISSUE TITLE
1.4.2 image is stuck in Pending state

### ISSUE THREAD

**Issue by Gilead** [containous/traefik-library-image#21] opened 2017-11-03 12:37 UTC
On our test rig we noticed that Traefik 1.4.2 becomes stuck in Pending state because "no suitable node (scheduling constraints not satisfied on 3 nodes; unsupported platform on 3 nodes)" even though its constraints are identical to other, successfully deployable services.

I'm happy to debug this further for you as I don't know if you can reproduce the issue or need any further information.

As it is we had to pin our images to version 1.4.1 as Traefik 1.4.2 wouldn't start at all.

**Comment by ldez** [comment] 2017-11-03 13:03
Duplicate of  #20

**Closed by ldez** 2017-11-03 13:03 UTC
