### ISSUE TITLE
v2.5.0 ERROR: no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by euri10** [containous/traefik-library-image#88] opened 2021-08-18 11:41 UTC
I get this when trying to upgrade, it seems like v2.5.0 is not available, 2.5 seems to be though

```
❯ dcup -d --build
Pulling traefik (traefik:v2.5.0)...
v2.5.0: Pulling from library/traefik
ERROR: no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by ldez** [comment] 2021-08-18 11:51
Hello,

It always happens because the images are built by Docker, we do not control the way they are published.

The image is currently under construction.

https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/


duplicate of  #85 #68 #39 #25 #23 #22 #20

**Closed as completed by ldez** 2021-08-18 11:51 UTC
Labels: duplicate
