### ISSUE TITLE
Missing amd64 manifest for 1.4.2

### ISSUE THREAD

**Issue by rheinwein** [containous/traefik-library-image#22] opened 2017-11-03 12:52 UTC
Upgrade to 1.4.2 is failing on amd64 because of a missing manifest. This seems to be the root cause of https://github.com/containous/traefik-library-image/issues/21

```
$ docker pull traefik:1.4.2
1.4.2: Pulling from library/traefik
no matching manifest for linux/amd64 in the manifest list entries
```

```
manifest-tool $ ./manifest-tool inspect traefik:1.4.2
Name:   traefik:1.4.2 (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:e9dcd8b3b0ded78d1edca42d087650c06a1d742092fe99d67ffb6a201c69ea45
 * Contains 2 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:1a1e91dc981bc6e5e232f6f24f3556be40ddd4fd1327e32b1e06b677d9d38a5c
1  Mfst Length: 739
1     Platform:
1           -      OS: linux
1           - OS Vers: 
1           - OS Feat: []
1           -    Arch: arm
1           - Variant: v6
1           - Feature: 
1     # Layers: 2
         layer 1: digest = sha256:8996ab8c9ae2c6afe7d318a3784c7ba1b1b72d4ae14cf515d4c1490aae91cab0
         layer 2: digest = sha256:ff8e8638d34c45934d48d89851bad4920602c02375f8b174b76507e20813491c

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:a4261837e99952784cc4b4fc27396f062f7ebb202dae4966eb764b5d93f97654
2  Mfst Length: 739
2     Platform:
2           -      OS: linux
2           - OS Vers: 
2           - OS Feat: []
2           -    Arch: arm64
2           - Variant: v8
2           - Feature: 
2     # Layers: 2
         layer 1: digest = sha256:78fe135ba97a13abc86dbe373975f0d0712d8aa6e540e09824b715a55d7e2ed3
         layer 2: digest = sha256:4aa5c73b733a0118e0ff1c0038a0892383d7a330471c5c5849c013a7263a801b
```

**Comment by ldez** [comment] 2017-11-03 13:03
Duplicate of  #20

**Closed by ldez** 2017-11-03 13:03 UTC

**Comment by ldez** [comment] 2017-11-03 13:05
Related to #3668
