### ISSUE TITLE
v2.3.6 amd64 image missing

### ISSUE THREAD

**Issue by viceice** [containous/traefik-library-image#85] opened 2020-12-18 06:31 UTC
The amd64 variants are missing on dockerhub for v2.3.6.

**Comment by ldez** [comment] 2020-12-18 06:34
the image is currently under construction

https://doi-janky.infosiftr.net/job/multiarch/view/images/view/traefik/


duplicate of  #68 #39 #25 #23 #22 #20

**Closed as completed by ldez** 2020-12-18 06:34 UTC
Labels: duplicate

**Comment by viceice** [comment] 2020-12-18 06:49
Thanks, didn't know 🤦‍♂️  So my renovate bot was to fast
